<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">

<head>
  <!--[if gte mso 9]>
  <xml>
    <o:OfficeDocumentSettings>
      <o:AllowPNG/>
      <o:PixelsPerInch>96</o:PixelsPerInch>
    </o:OfficeDocumentSettings>
  </xml>
  <![endif]-->
  <meta http-equiv='Content-type' content='text/html; charset=utf-8'/>
  <meta name='viewport' content='width=device-width, initial-scale=1, maximum-scale=1'/>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'/>
  <meta name='format-detection' content='date=no'/>
  <meta name='format-detection' content='address=no'/>
  <meta name='format-detection' content='telephone=no'/>
  <meta name='x-apple-disable-message-reformatting'/>
  <!--[if !mso]><!-->
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'/>
  <!--<![endif]-->
  <title>Email Template</title>

</head>
<body class='base-1'>
{% block main %}{% endblock %}
</body>
</html>
